### ISSUE TITLE
Suggestion: automatically confirm 'switch gpu' message

### ISSUE THREAD

**Issue by KazmiOG** [albertakhmetov/flowOSD#4]
Hi Albert,

I thought the best way to post a suggestion to you would be through GitHub. So here goes:

Could you make an option/setting that will automatically confirm or suppress the prompt that asks the user to confirm switching dGPU on/off?

Kind regards,

Kevin

**Comment by albertakhmetov** [comment]
This functionality was implemented in 2.0.1 release. Please, see the details [here](https://github.com/albertakhmetov/flowOSD/releases/tag/v2.0.1).
