### ISSUE TITLE
Charger type isn't supported - ASUS ROG Flow x16 (2023)

### ISSUE THREAD

**Issue by DigitalIQ** [albertakhmetov/flowOSD#5]
Hi there! First of all - awesome tool and really cool alternative to the orginal ASUS stuff!

Trying to open flowOSD 2.0.1, but getting this error message, followed by not starting flowOSD.
![grafik](https://user-images.githubusercontent.com/30226996/227261728-7d862c40-9249-4ee9-b6e5-6b4a5cfd70fd.png)

Running OS:
Windows 11 Pro 22H2 22621.1413

What am I doing wrong? (except using the Flow x13)

**Comment by albertakhmetov** [comment]
Hi,

This issue was fixed in [2.0.2 release](https://github.com/albertakhmetov/flowOSD/releases/tag/v2.0.2).
