### ISSUE TITLE
1 Bug or feature request

### ISSUE THREAD

**Issue by TimHuerzeler** [albertakhmetov/flowOSD#7]
Hi
I've noticed that when on DC Power ("Battery mode"),
when enabling High Refresh rate it gets disabled after 5 seconds.
Is there a way to have 120HZ on Battery? For writing with a stylus this
seems very useful to me.
Is this a Bug or a feature?
Love the Program otherwise.

**Comment by TimHuerzeler** [comment]
I looked at you're code and saw that it runs the update function and if it's on battery it sets it to low refresh rate, maybe only run this if a power source change is detected or if it is unplugged/plugged. If you don't constantly check the user would be able to decide on his own which mode he wants. Another option would be making a setting toggle to either let the User decide or the Program.

**Comment by albertakhmetov** [comment]
Hello,

Sorry for delay with the answer. Try to turn off "Control display refresh rate" option in Settings/General.

**Comment by TimHuerzeler** [comment]
Hi, no problem
Sadly this doesn't work for me.
Also a question, how did you design the UI? I looked at it in Visual Studio but can't really see anything. Would love to tweak some things like the battery display.

**Comment by albertakhmetov** [comment]
It seems that version 2.1.1 has "bug" when this parameter is ignored. I'll fix it ASAP.

Please, send me log file (c:\users\%user-name%\AppData\Local\flowOSD\log.txt) and your model's name to solve the issue with temperature.

ps. UI is defined by the code.

**Comment by TimHuerzeler** [comment]
[log.txt](https://github.com/albertakhmetov/flowOSD/files/11388220/log.txt)
Model name: ASUS ROG Flow X13 GV301RE-LJ117W

So there is no form with drag and drop for the UI?
also it's no xaml code right?

**Comment by albertakhmetov** [comment]
The issue with Refresh Rate was resolved in [2.1.2](https://github.com/albertakhmetov/flowOSD/releases/tag/v2.1.2) release. CPU temperature monitoring was updated, but not tested on the GV301RE model.
